# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbeltprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotecontribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteauthor', models.CharField(max_length=100)),
                ('quotemessage', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_contributions', to='pythonbeltprojectapp.Userinfo')),
            ],
        ),
    ]
