# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbeltprojectapp', '0002_quotecontribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotefavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteauthorfav', models.CharField(max_length=100)),
                ('quotemessagefav', models.CharField(max_length=500)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_favorites', to='pythonbeltprojectapp.Quotecontribute')),
            ],
        ),
    ]
