# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbeltprojectapp', '0004_quotefavorites_userfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='DOB',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
